#!/usr/bin/env bash

name=$1
#remote=$2
remote=$1
disk="$name.img"
#card="enp2s0"
card="eno1"
user="admisol"

if [ ! -f "$disk" ]; then
    qemu-img create -f raw "$disk" 8G
fi

#lan
lan="lan-br"
landev="lan-$name"
lanmac=$(./qemu-mac "$landev")

#lan bridge
if [ ! -d "/sys/devices/virtual/net/$lan" ]; then
    sudo ip link add dev "$lan" type bridge
    sudo ip link set dev "$lan" up
fi

#lan device
if [ ! -d "/sys/devices/virtual/net/$landev" ]; then
    sudo ip tuntap add dev "$landev" mode tap user "$user" group "$user"
    sudo ip link set dev "$landev" up
    sudo ip link set dev "$landev" master "$lan"
fi

if [ "$name" -eq "7000" ]; then
	#wan
	wan="wan-br"
	wandev="wan-$name"
	wanmac=$(./qemu-mac "$wandev")

	#wan bridge
	if [ ! -d "/sys/devices/virtual/net/$wan" ]; then
		sudo ip link add dev "$wan" type bridge
		sudo ip link set dev "$wan" up

		sudo ip address flush dev "$card"
		sudo ip link set "$card" master "$wan"
	fi

	#wan device
	if [ ! -d "/sys/devices/virtual/net/$wandev" ]; then
		sudo ip tuntap add dev "$wandev" mode tap user "$user" group "$user"
		sudo ip link set dev "$wandev" up
		sudo ip link set dev "$wandev" master "$wan"
	fi
fi

#boot
if [ "$name" -eq "7000" ]; then
	qemu-system-x86_64 \
        	-m 256M \
	        -boot order=cnd,menu=on \
	        -drive file="$disk",format=raw \
	        -cdrom mini.iso \
	        -device e1000,mac="$lanmac",netdev=lan \
	        -netdev tap,id=lan,ifname="$landev",script=no,downscript=no \
	        -device e1000,mac="$wanmac",netdev=wan \
	        -netdev tap,id=wan,ifname="$wandev",script=no,downscript=no \
	        -vga qxl \
	        -spice "port=$remote,disable-ticketing" \
	        -enable-kvm \
	        -daemonize
else
        qemu-system-x86_64 \
                -m 256M \
                -boot order=cnd,menu=on \
                -drive file="$disk",format=raw \
                -cdrom mini.iso \
                -device e1000,mac="$lanmac",netdev=lan \
                -netdev tap,id=lan,ifname="$landev",script=no,downscript=no \
                -vga qxl \
                -spice "port=$remote,disable-ticketing" \
                -enable-kvm \
                -daemonize
fi
